### ISSUE TITLE
errors occurred when timer running

### ISSUE THREAD

**Issue by brsvh** [ksqsf/org-xlatex#1]
I cautiously duplicated your package into the scratch buffer and then loaded it using `eval-buffer`. However, upon activating `org-xlatex-mode` in the org buffer containing equations, I encountered timer errors :sob:

```
Error running timer ‘org-xlatex--timer-function’: (invalid-function (lambda (&rest) "Preview at point if the point is at a math formula." (if (and (derived-mode-p 'org-mode) (texmathp)) (org-xlatex-preview) (org-xlatex--hide))))
```

I am somewhat uncertain as to whether I am missing something.

<details>
<summary>versions</summary>

- Emacs: GNU Emacs 29.0.91 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-06-05

- `org`: "9.6.1"

- `AUCTeX`: "13.1.9"

</details>

Incidentally, your `Package-Requires` field is missing `AUCTeX` because you are using `texmathp`.

**Comment by ksqsf** [comment]
Just pushed a change. Would you please try again?

**Comment by brsvh** [comment]
It works now :+1:
![image](https://github.com/ksqsf/org-xlatex/assets/63050399/9a1f44cc-e1b1-4bc6-8889-8f39b5798dd1)

**Comment by brsvh** [comment]
Something unrelated to this thread:

When I call the `org-xlatex-preview` function in a buffer with the Org XLaTeX minor mode activated, the rendered preview only appears for a very brief moment, possibly less than 0.1 seconds.

So I have a guessing based solely on its name, `org-xlatex-preview` appears to be intended for temporary formula previewing, perhaps when `org-xlatex-mode` is not yet activated. 

Then I try to use this command in other buffer which `org-xlatex-mode` is not activated, it creates a completely black child frame at the top of all frames, so sucks.   And I read the codes, its works depends on `org-xlatex-frame`.  I think it should create a temporary frame and there ought to be an appropriate moment to dispose of the temporary frame.

If you think it is a bug, maybe it should be track in another thread.

**Comment by ksqsf** [comment]
I agree it's confusing. I'll simply make `org-xlatex-preview` non-interactive.
