### ISSUE TITLE
如何手动调整预览框出现位置？

### ISSUE THREAD

**Issue by QuarterHeaven** [ksqsf/org-xlatex#2]
使用了懒猫的 awesome-tab 插件，导致预览框出现了 tab。设置为隐藏后，预览框出现位置整体向上移动了一部分，公式被遮挡了一半：
![image](https://github.com/ksqsf/org-xlatex/assets/41909950/9c542408-32a5-437b-99ce-ea44c7c3ef2f)
我想将预览框向下调整，设置了 org-xlatex-frame-parameters top 参数，似乎没有作用？请问这个该如何调整呢

**Comment by ksqsf** [comment]
一时没搞懂 awesome-tab（和 tab-line）是怎么影响到座标的，所以还不知道怎么修复这个问题。暂时添加了两个配置选项，`org-xlatex-size-function` 和 `org-xlatex-position-function`，目前可以用 `org-xlatex-position-function` 来手动定位预览位置：

```elisp
(setq org-xlatex-position-function
      (cl-function (lambda ((x. y))
         (cons x (+ y 向下移动多少像素)))))
```

**Comment by ksqsf** [comment]
刚才忘说了，awesome-tab 兼容性问题已经解决，现在不需要做特殊配置了。
